### ISSUE TITLE
Invalid Attribut 'args' error

### ISSUE THREAD

**Issue by codingfabi** [ukoethe/bomberman_rl#4]
When I try to run the game, I get the following error message: 

`AttributeError: 'BombeRLeWorld' object has no attribute 'args'`

I'm using a windows 10 machine with Python 3.9.1

**Comment by codingfabi** [comment]
@fdraxler I think this is a problem with your latest commit (d002ad8) and line 63 in the `environments.py`

**Comment by fdraxler** [comment]
Thanks for the report, I closed it.
